version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: fiap
      POSTGRES_PASSWORD: fiap@2025
      POSTGRES_DB: video-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
